version: "3.7"

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress
    user: "1000:1000"
    volumes:
      - ./wordpress_data:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - wordpress_network
    restart: always

  db:
    image: mysql:8.0
    container_name: wordpressdb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - wordpress_network
    restart: always

  nginx:
    image: arm64v8/nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
      - certbot_www:/var/www/certbot
      - ./wordpress_data:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - wordpress
      - db
    networks:
      - wordpress_network
    restart: always

  certbot:
    image: certbot/certbot:arm64v8-latest
    container_name: certbot
    volumes:
      - certbot_etc:/etc/letsencrypt
      - certbot_var:/var/lib/letsencrypt
      - certbot_www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done'"
    networks:
      - wordpress_network
    restart: always

volumes:
  certbot_etc:
  certbot_var:
  certbot_www:

networks:
  wordpress_network:
